import Head from "next/head";
import Image from "next/image";
import Link from "next/link";
import {
  List,
  ListItem,
  Card,
  CardMedia,
  CardContent,
  CardActions,
} from "@/components/mui";
import Layout from "@/components/Layout";
import Heading from "@/components/Heading";
import { AllPosts } from "@/lib/hygraph/queries";
import backgroundImg from "@/images/mountain_color.webp";
import { useTheme } from "@mui/material/styles";

export default function Blog({ ssd = [] }) {
  const theme = useTheme();
  const buttonColor = theme.palette.secondary.main;
  // console.log("ssd", ssd);
  return (
    <div
      style={{
        backgroundImage: `url(${backgroundImg.src})`,
        backgroundSize: "cover",
        backgroundAttachment: "fixed",
        width: "100%",
        minHeight: "100vh",
      }}
    >
      <Head>
        <title>Eclectic Shop | Blog</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2" sx={{ color: "white" }}>
          Blog Articles
        </Heading>
        <List component={"ol"} sx={{ listStyle: "none" }}>
          {ssd.map(({ id, title, slug, heroImage: { url } }) => (
            <ListItem key={id} sx={{ position: "relative" }}>
              <Card
                component={"article"}
                sx={{
                  width: "100%",
                  backgroundColor: "hsla(90, 0%, 0%, 0.5)",
                  // zIndex: 1,
                  display: "grid",
                  gridTemplateColumns: "1fr 1fr",
                  borderRadius: "4px",
                  overflow: "hidden",
                  justifyContent: "space-between",
                  position: "relative",
                }}
              >
                <div
                  style={{
                    backdropFilter: "blur(10px)",
                    position: "absolute",
                    minWidth: "100%",
                    minHeight: "100%",
                    zIndex: 0,
                  }}
                />
                <div
                  style={{
                    display: "flex",
                    flexDirection: "column",
                    alignItems: "start",
                    width: "100%",
                    padding: "0.5em",
                    zIndex: 1,
                    minWidth: "6em",
                  }}
                >
                  <CardContent sx={{ padding: "8px" }}>
                    <Heading component="h4" color="white" sx={{ zIndex: 1 }}>
                      {title}
                    </Heading>
                  </CardContent>
                  <CardActions>
                    <Link
                      href={`/blog/${slug}`}
                      style={{ color: `${buttonColor}`, fontSize: "0.8rem" }}
                    >
                      Read more...
                    </Link>
                  </CardActions>
                </div>
                <CardMedia
                  sx={{ display: "grid", placeContent: "center", zIndex: 1, justifySelf: "end" }}
                >
                  <Image alt={title} src={url} width="300" height="200" />
                </CardMedia>
              </Card>
            </ListItem>
          ))}
        </List>
      </Layout>
    </div>
  );
}

export const getStaticProps = async () => {
  const allPosts = await fetch(process.env.HYGRAPH_ENDPOINT, {
    method: "POST",
    headers: {
      "Content-Type": `application/json; charset="UTF-8`,
      Authorization: `Bearer ${process.env.HYGRAPH_TOKEN}`, // "Authorization"
    },
    body: JSON.stringify({
      query: AllPosts,
    }),
  })
    .then((res) => res.json())
    .catch((err) => console.log(err));
  console.log("allposts", allPosts);
  const posts = allPosts.data.blogPosts;
  console.log("posts", posts);
  return {
    props: {
      ssd: posts,
    },
  };
};
