import Head from "next/head";
import { useRouter } from "next/router";

import Layout from "@/components/Layout";
import Heading from "@/components/Heading";
import Paragraph from "@/components/Paragraph";
import backgroundImg from "@/images/mountain_color.webp";
import { useTheme } from "@mui/material/styles";

export default function ThankYouPage() {
  const router = useRouter();
  const {
    query: { receiptURL },
  } = router;
  const theme = useTheme();
  const buttonColor = theme.palette.secondary.main;
  const textShadow = theme.textShadow.filter;
  return (
    <div style={{
      backgroundImage: `url(${backgroundImg.src})`,
      backgroundSize: "cover",
      backgroundAttachment: "fixed",
      width: "100vw",
      minHeight: "100vh"}}>
      <Head>
        <title>Eclectic Order Confirmation</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Layout>
        <Heading component="h2" sx={{ color: "white" }}>Thank you for your order at the Eclectic Shop!</Heading>
        <Paragraph sx={{ color: "white", filter: `${textShadow}`, padding: "1em", fontSize: "1.5rem" }}>
          You can view a copy of your receipt <a href={receiptURL} target="_blank" style={{ color: `${buttonColor}` }} >here</a>
        </Paragraph>
      </Layout>
    </div>
  );
}